version: 2.1

jobs:
  setup:
    machine:
      image: ubuntu-2004:current
    resource_class: large
    steps:
      - checkout
      - run:
          name: "Syncing Sources"
          command: source scripts/sync.sh
      - run:
          name: "Initializing Build System"
          command: source scripts/build.sh
      - run:
          name: "Uploading Output"
          command: source scripts/upload.sh
workflows:
  setup:
    jobs:
      - setup:
          context: org-global
